build:
  image: snickch/buildx:latest
  stage: build
  services:
    - name: docker:dind
      alias: docker

  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    PLATFORM: linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
  - docker run --privileged --rm tonistiigi/binfmt --install all
  - docker buildx create --use

  script:
    - sed -i 's|__VERSION__|'$CI_COMMIT_REF_NAME'|g' components/AppFooter.vue
    - sed -i 's|__VERSION_LINK__|https://github.com/6px/Inventronic/releases/tag/'$CI_COMMIT_REF_NAME'|g' components/AppFooter.vue
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker buildx build -f ./docker/Dockerfile -t "$IMAGE_TAG" --platform "$PLATFORM" --cache-from "$IMAGE_TAG" --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USER --password-stdin
    - docker tag $IMAGE_TAG jonathanfoucher/inventronic:latest
    - docker tag $IMAGE_TAG jonathanfoucher/inventronic:$CI_COMMIT_TAG
    - docker push jonathanfoucher/inventronic:latest
    - docker push jonathanfoucher/inventronic:$CI_COMMIT_TAG
  only:
    - tags

