build:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
      
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - sed -i 's|__VERSION__|'$CI_COMMIT_REF_NAME'|g' components/AppFooter.vue
    - sed -i 's|__VERSION_LINK__|https://github.com/6px/Inventronic/releases/tag/'$CI_COMMIT_REF_NAME'|g' components/AppFooter.vue
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - cd docker && docker build -f ./docker/Dockerfile -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USER --password-stdin
    - docker tag $IMAGE_TAG jonathanfoucher/inventronic:latest
    - docker tag $IMAGE_TAG jonathanfoucher/inventronic:$CI_COMMIT_TAG
    - docker push jonathanfoucher/inventronic:latest
    - docker push jonathanfoucher/inventronic:$CI_COMMIT_TAG
  only:
    - tags

