build:
  image: docker:24
  stage: build
  services:
    - docker:24-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - sed -i 's|__VERSION__|'$CI_COMMIT_REF_NAME'|g' components/AppFooter.vue
    - sed -i 's|__VERSION_LINK__|https://github.com/6px/Inventronic/releases/tag/'$CI_COMMIT_REF_NAME'|g' components/AppFooter.vue
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:latest
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD 
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG jonathanfoucher/inventronic:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG jonathanfoucher/inventronic:$CI_COMMIT_REF_SLUG
    - docker push jonathanfoucher/inventronic:latest
    - docker push jonathanfoucher/inventronic:$CI_COMMIT_REF_SLUG
  only:
    - main

